### ISSUE TITLE
可以在.py文件里面写上路径吗？

### ISSUE THREAD

**Issue by JianbingDong** [zizhaozhang/unet-tensorflow-keras#5]
你好：
        最近在学习深度学习，大神的代码写的非常高深。
        我按照你的readme的步骤来操作的时候，系统会出现错误，提示说：系统找不到指定的路径，我已经将你的说明中的your-data-path改成了我自己的文件夹了（使用的是绝对路径），然后就出现了这个问题。
         所以我想请教一下，可以在.py文件中声明相关的路径吗？还有，总共需要自己设置几个路径呢？
        还请大神不吝赐教。
        谢谢！！

**Comment by zizhaozhang** [comment]
Hi  I can not understand your question based on your description. Maybe you can screenshoot me the errors?
